spring.application.name=MealManagement
# Server port
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/final_mess
spring.datasource.username=root
spring.datasource.password=Prantascode
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update      
spring.jpa.show-sql=true       
spring.jpa.properties.hibernate.format_sql=true            
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT secret key (used in JwtUtil)
jwt.secret=YourSuperSecretKey12345
jwt.expiration=86400000   # 1 day in milliseconds

gemini.api.key=AIzaSyDuIW3zpCNt-k2q3J0vYajMndOPdTTWJA4

google.oauth.client-id=1048538523752-tqt5jrrluotrk6iugk4qj2kt09n5l9dr.apps.googleusercontent.com
google.oauth.client-secret=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
google.oauth.redirect-uri=http://localhost:8080/api/google/oauth/callback
google.oauth.scope=https://www.googleapis.com/auth/gmail.send