spring.profiles.active=local

spring.application.name=MealManagement
# Server port
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=${JWT_SECRET}

google.oauth.client-id=${GOOGLE_OAUTH_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
google.oauth.redirect-uri=${GOOGLE_OAUTH_REDIRECT_URI}
google.oauth.scope=${GOOGLE_OAUTH_SCOPE}

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update      
spring.jpa.show-sql=true       
spring.jpa.properties.hibernate.format_sql=true            
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.expiration=86400000   # 1 day in milliseconds

gemini.api.key=${GEMINI_API_KEY}